---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: sleep infinity

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
      remote_tmp: /tmp/.ansible/tmp
      roles_path: /Users/igorgurin/Desktop/дз/3_ansible_roles/roles
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "1"
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
