---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install OpenSSH server
      ansible.builtin.apt:
        name: openssh-server
        state: present
        update_cache: true
